version: "3.9"
services:
  # Distributed query engine for various types
  # of data sources
  trino:
    ports:
      - "8080:8080"
    container_name: datalake-trino
    image: "trinodb/trino:410"
    hostname: trino
    volumes:
      - ./trino/etc:/usr/lib/trino/etc:ro
      - ./trino/catalog:/etc/trino/catalog
    depends_on:
      - hive-metastore

  # We use PostgreSQL to store Hive metadata about
  # how the datafile are mapped to schemas and tables
  metastore_db:
    container_name: datalake-metastore-db
    image: postgres:11
    hostname: metastore_db
    ports:
      - '5433:5432' # Access via Thrift protocol
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore

  # Expose service to get metadata, which is a repository of metadata about the tables, 
  # such as database names, table names, schema and data location of each table
  hive-metastore:
    container_name: datalake-hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    hostname: hive-metastore
    ports:
      - '${HIVE_METASTORE_PORT}:${HIVE_METASTORE_PORT}' # Access via Thrift protocol
    env_file:
      - env/.env.hive-metastore
    depends_on:
      - metastore_db
      
  # Parquet files stored in MinIO object storage
  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}" # For API requests
      - "${MINIO_UI_PORT}:${MINIO_UI_PORT}" # For UI access
    volumes:
      - minio_storage:/data
    env_file:
      - env/.env.minio
    command: server --console-address ":${MINIO_UI_PORT}" /data

volumes:
  minio_storage: